language: lisp

env:
  matrix:
    # - LISP=abcl
    - LISP=sbcl
    # - LISP=sbcl32
    # - LISP=ccl
    # - LISP=ccl32
    # - LISP=clisp
    # - LISP=clisp32
    # - LISP=cmucl
    # - LISP=ecl

install:
  - sudo pip install tox
  - if [ -x ./install.sh ] && head -2 ./install.sh | grep '^#cl-travis' > /dev/null;
    then
      ./install.sh;
    else
      curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | sh;
    fi
  - wget http://common-lisp.net/project/xcvb/cl-launch/cl-launch.tar.gz
  - mkdir "$HOME/cl-launch"
  - tar zxf cl-launch.tar.gz --strip-components=1 -C "$HOME/cl-launch/"
  - sudo bash "$HOME/cl-launch/cl-launch.sh" -I "$HOME/cl-launch/" -o "/usr/local/bin/cl-launch" -B install

script:
  - tox
